// examples/react-dom-worker/src/worker/svelte/Notes.svelte
<script lang="ts">
  /**
   * 'notes' — the notes composer from the Vue demo, Svelte 5 runes style:
   * draft + notes are `$state`, the `{#each}` list and `{length}` readout
   * update through the proxy DOM, and 'noteAdded' emits to the shell.
   */
  import { emit } from '@atolljs/svelte-island/worker';

  let { title = 'svelte island' }: { title?: string } = $props();
  let draft = $state('');
  let notes = $state<string[]>([]);

  const add = (): void => {
    const text = draft.trim();
    if (text === '') return;
    notes = [...notes, text];
    draft = '';
    emit('noteAdded', { text, total: notes.length });
  };
</script>

<div class="svelte-notes">
  <h3 class="vanilla-heading">{title}</h3>
  <div class="atoll-map-places">
    <input
      placeholder="write a note…"
      value={draft}
      oninput={(e) => { draft = e.currentTarget.value; }}
      onkeydown={(e) => { if (e.key === 'Enter') add(); }}
    />
    <button class="atoll-map-place-btn" onclick={add}>add</button>
  </div>
  <ul class="vanilla-log">
    {#each notes as n, i (i)}
      <li class="vanilla-log-line">{n}</li>
    {/each}
  </ul>
  <div class="vanilla-readout">{notes.length} note(s) — state lives in the worker</div>
</div>

// examples/mfe/worker/vue/Notes.vue
<script setup lang="ts">
/**
 * 'notes' — a notes composer SFC running inside the worker. Vue's
 * createRenderer is bound to the instance's proxy DOM; `emit` rides the
 * island's event channel back to whatever shell mounted it.
 */
import { ref } from 'vue';
import { emit } from '@atolljs/vue-island/worker';

const props = withDefaults(defineProps<{ title?: string }>(), { title: 'vue mfe' });
const draft = ref('');
const notes = ref<string[]>([]);
const add = (): void => {
  const text = draft.value.trim();
  if (text === '') return;
  notes.value.push(text);
  draft.value = '';
  emit('noteAdded', { text, total: notes.value.length });
};
</script>

<template>
  <div class="mfe-card">
    <h3 class="mfe-heading">{{ props.title }}</h3>
    <div class="mfe-row">
      <input v-model="draft" placeholder="write a note…" @keydown.enter="add" />
      <button class="mfe-btn" @click="add">add</button>
    </div>
    <ul class="mfe-list">
      <li v-for="(n, i) in notes" :key="i" class="mfe-list-line">{{ n }}</li>
    </ul>
    <div class="mfe-readout">{{ notes.length }} note(s) — Vue state lives in the worker</div>
  </div>
</template>
