// examples/react-host/src/shell.tsx
/**
 * React host — FIVE worker-rendered micro-frontends, five frameworks.
 *
 * The shell imports only CONTRACT modules (`../../mfe/contracts/*`): each is
 * a framework-free `{ app, props schema, events schemas, worker factory }`
 * object. `islandComponent(contract)` produces a typed facade — props and
 * `onEvent` payloads come straight from the contract's `z` schemas — and
 * the contract's `worker` field supplies the connection, so the call sites
 * need no worker wiring at all.
 *
 * Nothing in this bundle imports Vue, Solid, Svelte, or Angular — those
 * runtimes exist only inside their own worker chunks.
 */
import { Suspense, useState } from 'react';
import type { ReactElement } from 'react';
import { createRoot } from 'react-dom/client';
import { islandComponent } from '@atolljs/react-island';
import { initDevtools } from '@atolljs/devtools';
import type { IslandHandle, Mode } from '@atolljs/islands';

// Instrument before islands mount — the sink must exist when workers
// spawn for their events to forward. No-op unless the URL carries
// ?__atoll_devtools.
initDevtools({
  session: { name: 'islands-react-host', framework: 'react' },
  // Relative dashboard path — mounted hosts (the docs demo tree) ship
  // __atoll/ inside the app's own folder; absolute /__atoll/ would escape
  // a sub-path mount like consumer/<demo>/.
  overlay: { src: '__atoll/?mini=1' },
});
import counterContract from '../../mfe/contracts/counter.contract';
import notesContract from '../../mfe/contracts/notes.contract';
import tickerContract from '../../mfe/contracts/ticker.contract';
import dialContract from '../../mfe/contracts/dial.contract';
import checkoutContract from '../../mfe/contracts/checkout.contract';

/* Each facade is typed end-to-end off its contract: `CounterIsland` takes
 * `{ label?: string }` props and an `onEvent` narrowed to
 * 'incremented' → { count, label }. */
const CounterIsland = islandComponent(counterContract);   // React in the worker
const NotesIsland = islandComponent(notesContract);       // Vue
const TickerIsland = islandComponent(tickerContract);     // Solid
const DialIsland = islandComponent(dialContract);         // Svelte
const CheckoutIsland = islandComponent(checkoutContract); // Angular

// SharedArrayBuffer only exists in cross-origin-isolated contexts — without
// COOP/COEP (and when coi-sw.js can't take, e.g. first visit) the doorbell
// can't bind, so islands run their 50ms poll transport instead of push.
const mode: Mode =
  typeof SharedArrayBuffer !== 'undefined' &&
  (typeof window.crossOriginIsolated === 'undefined' || window.crossOriginIsolated)
    ? 'push'
    : 'poll';

/** The call-site code rendered under each island — the shell code itself. */
const SNIPPETS = {
  counter: `const CounterIsland = islandComponent(counterContract)

<CounterIsland label="alpha" onEvent={(name, p) => …} />`,
  notes: `const NotesIsland = islandComponent(notesContract)

<NotesIsland title="vue island" onEvent={(name, p) => …} />`,
  ticker: `const TickerIsland = islandComponent(tickerContract)

<TickerIsland label="pulse" intervalMs={1000} onEvent={…} />`,
  dial: `const DialIsland = islandComponent(dialContract)

<DialIsland label="level" value={40} onEvent={…} />`,
  checkout: `const CheckoutIsland = islandComponent(checkoutContract)

<CheckoutIsland label="cart" total={42} onEvent={…} />`,
};

function Shell(): ReactElement {
  const [status, setStatus] = useState('mounting islands…');
  const [pids, setPids] = useState<Record<string, string>>({});
  const ready =
    (key: string) =>
    (handle: IslandHandle): void =>
      setPids((p) => ({ ...p, [key]: `worker ${handle.pid}` }));

  return (
    <>
      <h1>React shell — five frameworks inside workers</h1>
      <p style={{ font: '12px monospace', color: '#9aa4b2', marginTop: -8 }}>
        every island mounts through a framework-free <code>*.contract.ts</code> — props and events
        type-check at compile time AND validate at the worker boundary.
      </p>
      <div id="status-line">{status}</div>

      <section className="island">
        <div className="island-head">
          <span>counter — React worker</span>
          <span className="badge">{pids.counter ?? 'worker …'}</span>
        </div>
        <Suspense fallback={null}>
          <CounterIsland
            label="alpha"
            mode={mode}
            containerProps={{ className: 'island-root' }}
            onReady={ready('counter')}
            onEvent={(name, payload) => {
              if (name === 'incremented')
                setStatus(`${payload.label} counter → ${payload.count} (React state stayed in the worker)`);
            }}
          />
        </Suspense>
        <pre className="island-code"><code>{SNIPPETS.counter}</code></pre>
      </section>

      <section className="island">
        <div className="island-head">
          <span>notes — Vue worker (createRenderer on the proxy DOM)</span>
          <span className="badge">{pids.notes ?? 'worker …'}</span>
        </div>
        <Suspense fallback={null}>
          <NotesIsland
            title="vue island"
            mode={mode}
            containerProps={{ className: 'island-root' }}
            onReady={ready('notes')}
            onEvent={(name, payload) => {
              if (name === 'noteAdded')
                setStatus(`notes island emitted noteAdded → "${payload.text}" (${payload.total} total)`);
            }}
          />
        </Suspense>
        <pre className="island-code"><code>{SNIPPETS.notes}</code></pre>
      </section>

      <section className="island">
        <div className="island-head">
          <span>ticker — Solid worker (timer-driven emits)</span>
          <span className="badge">{pids.ticker ?? 'worker …'}</span>
        </div>
        <Suspense fallback={null}>
          <TickerIsland
            label="pulse"
            intervalMs={1000}
            mode={mode}
            containerProps={{ className: 'island-root' }}
            onReady={ready('ticker')}
            onEvent={(name, payload) => {
              if (name === 'tick') setStatus(`ticker island emitted tick → ${payload.count}`);
            }}
          />
        </Suspense>
        <pre className="island-code"><code>{SNIPPETS.ticker}</code></pre>
      </section>

      <section className="island">
        <div className="island-head">
          <span>dial — Svelte worker (mount() on the proxy DOM)</span>
          <span className="badge">{pids.dial ?? 'worker …'}</span>
        </div>
        <Suspense fallback={null}>
          <DialIsland
            label="level"
            value={40}
            mode={mode}
            containerProps={{ className: 'island-root' }}
            onReady={ready('dial')}
            onEvent={(name, payload) => {
              if (name === 'changed') setStatus(`dial island emitted changed → ${payload.value}`);
            }}
          />
        </Suspense>
        <pre className="island-code"><code>{SNIPPETS.dial}</code></pre>
      </section>

      <section className="island">
        <div className="island-head">
          <span>checkout — Angular worker (JIT + zoneless, signal inputs)</span>
          <span className="badge">{pids.checkout ?? 'worker …'}</span>
        </div>
        <Suspense fallback={null}>
          <CheckoutIsland
            label="cart"
            total={42}
            mode={mode}
            containerProps={{ className: 'island-root' }}
            onReady={ready('checkout')}
            onEvent={(name, payload) => {
              if (name === 'paid') setStatus(`checkout island emitted paid → $${payload.total}`);
            }}
          />
        </Suspense>
        <pre className="island-code"><code>{SNIPPETS.checkout}</code></pre>
      </section>
    </>
  );
}

const rootEl = document.getElementById('root');
if (rootEl) createRoot(rootEl).render(<Shell />);

// examples/solid-host/src/shell.tsx
/** @jsxImportSource solid-js */
/**
 * Solid host — FIVE worker-rendered micro-frontends, five frameworks.
 *
 * The shell imports only CONTRACT modules (`../../mfe/contracts/*`):
 * `islandComponent(contract)` produces a component whose props are the
 * contract's prop type, `onEvent` narrows to the declared event vocabulary,
 * and the contract's `worker` field supplies the connection — call sites
 * wire nothing.
 *
 * Nothing in this bundle imports React, Vue, Svelte, or Angular — those
 * runtimes exist only inside their own worker chunks.
 */
import { createSignal } from 'solid-js';
import { render } from 'solid-js/web';
import { islandComponent } from '@atolljs/solid-island';
import { initDevtools } from '@atolljs/devtools';
import type { IslandHandle } from '@atolljs/islands';

// Instrument before islands mount — the sink must exist when workers
// spawn for their events to forward. No-op unless the URL carries
// ?__atoll_devtools.
initDevtools({
  session: { name: 'islands-solid-host' },
  // Relative dashboard path — mounted hosts (the docs demo tree) ship
  // __atoll/ inside the app's own folder; absolute /__atoll/ would escape
  // a sub-path mount like consumer/<demo>/.
  overlay: { src: '__atoll/?mini=1' },
});
import counterContract from '../../mfe/contracts/counter.contract';
import notesContract from '../../mfe/contracts/notes.contract';
import tickerContract from '../../mfe/contracts/ticker.contract';
import dialContract from '../../mfe/contracts/dial.contract';
import checkoutContract from '../../mfe/contracts/checkout.contract';

const CounterIsland = islandComponent(counterContract);   // React in the worker
const NotesIsland = islandComponent(notesContract);       // Vue
const TickerIsland = islandComponent(tickerContract);     // Solid
const DialIsland = islandComponent(dialContract);         // Svelte
const CheckoutIsland = islandComponent(checkoutContract); // Angular

// No SharedArrayBuffer without COOP/COEP — the doorbell option travels with
// the client (workerOptions.doorbell), and a doorbell-free client's 'push'
// mode falls back to 50ms polling automatically.
const isolated =
  typeof SharedArrayBuffer !== 'undefined' &&
  (typeof window.crossOriginIsolated === 'undefined' || window.crossOriginIsolated);
const transport = { workerOptions: { doorbell: isolated } };

/** The call-site code rendered under each island — this file's own idiom. */
const SNIPPETS = {
  counter: `const CounterIsland = islandComponent(counterContract)

<CounterIsland label="alpha" onEvent={(name, p) => …} />`,
  notes: `const NotesIsland = islandComponent(notesContract)

<NotesIsland title="vue island" onEvent={(name, p) => …} />`,
  ticker: `const TickerIsland = islandComponent(tickerContract)

<TickerIsland label="pulse" intervalMs={1000} onEvent={…} />`,
  dial: `const DialIsland = islandComponent(dialContract)

<DialIsland label="level" value={40} onEvent={…} />`,
  checkout: `const CheckoutIsland = islandComponent(checkoutContract)

<CheckoutIsland label="cart" total={42} onEvent={…} />`,
};

function Shell() {
  const [status, setStatus] = createSignal('mounting islands…');
  const [pids, setPids] = createSignal<Record<string, string>>({});

  const ready =
    (key: string) =>
    (handle: IslandHandle): void => {
      setPids((p) => ({ ...p, [key]: `worker ${handle.pid}` }));
    };

  return (
    <>
      <h1>Solid shell — five frameworks inside workers</h1>
      <p style={{ font: '12px monospace', color: '#9aa4b2', 'margin-top': '-8px' }}>
        every island mounts through a framework-free <code>*.contract.ts</code> — props and{' '}
        <code>onEvent</code> payloads type off the contract's z schemas.
      </p>
      <div id="status-line">{status()}</div>

      <section class="island">
        <div class="island-head">
          <span>counter — React worker</span>
          <span class="badge">{pids().counter ?? 'worker …'}</span>
        </div>
        <CounterIsland
          label="alpha"
          {...transport}
          containerProps={{ class: 'island-root' }}
          onReady={ready('counter')}
          onEvent={(name, payload) => {
            if (name === 'incremented')
              setStatus(`${payload.label} counter → ${payload.count} (React state stayed in the worker)`);
          }}
        />
        <pre class="island-code">{SNIPPETS.counter}</pre>
      </section>

      <section class="island">
        <div class="island-head">
          <span>notes — Vue worker (createRenderer on the proxy DOM)</span>
          <span class="badge">{pids().notes ?? 'worker …'}</span>
        </div>
        <NotesIsland
          title="vue island"
          {...transport}
          containerProps={{ class: 'island-root' }}
          onReady={ready('notes')}
          onEvent={(name, payload) => {
            if (name === 'noteAdded')
              setStatus(`notes island emitted noteAdded → "${payload.text}" (${payload.total} total)`);
          }}
        />
        <pre class="island-code">{SNIPPETS.notes}</pre>
      </section>

      <section class="island">
        <div class="island-head">
          <span>ticker — Solid worker (timer-driven emits)</span>
          <span class="badge">{pids().ticker ?? 'worker …'}</span>
        </div>
        <TickerIsland
          label="pulse"
          intervalMs={1000}
          {...transport}
          containerProps={{ class: 'island-root' }}
          onReady={ready('ticker')}
          onEvent={(name, payload) => {
            if (name === 'tick') setStatus(`ticker island emitted tick → ${payload.count}`);
          }}
        />
        <pre class="island-code">{SNIPPETS.ticker}</pre>
      </section>

      <section class="island">
        <div class="island-head">
          <span>dial — Svelte worker (mount() on the proxy DOM)</span>
          <span class="badge">{pids().dial ?? 'worker …'}</span>
        </div>
        <DialIsland
          label="level"
          value={40}
          {...transport}
          containerProps={{ class: 'island-root' }}
          onReady={ready('dial')}
          onEvent={(name, payload) => {
            if (name === 'changed') setStatus(`dial island emitted changed → ${payload.value}`);
          }}
        />
        <pre class="island-code">{SNIPPETS.dial}</pre>
      </section>

      <section class="island">
        <div class="island-head">
          <span>checkout — Angular worker (JIT + zoneless, signal inputs)</span>
          <span class="badge">{pids().checkout ?? 'worker …'}</span>
        </div>
        <CheckoutIsland
          label="cart"
          total={42}
          {...transport}
          containerProps={{ class: 'island-root' }}
          onReady={ready('checkout')}
          onEvent={(name, payload) => {
            if (name === 'paid') setStatus(`checkout island emitted paid → $${payload.total}`);
          }}
        />
        <pre class="island-code">{SNIPPETS.checkout}</pre>
      </section>
    </>
  );
}

const rootEl = document.getElementById('root');
if (rootEl) render(() => <Shell />, rootEl);
