// examples/react/src/main.tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { initDevtools } from '@atolljs/devtools';
import { App } from './App';
import './styles.css';

// Instrument before the pool's first task call — the sink must be installed
// when workers spawn for their events to forward over the task channel.
// No-op unless the URL carries ?__atoll_devtools.
initDevtools({
  session: { name: 'incidents-react', framework: 'react' },
  // Relative dashboard path — mounted hosts (the docs demo tree) ship
  // __atoll/ inside the app's own folder; absolute /__atoll/ would escape
  // a sub-path mount like consumer/<demo>/.
  overlay: { src: '__atoll/?mini=1' },
});

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);

// examples/solid/src/index.tsx
import { render } from 'solid-js/web';
import { initDevtools } from '@atolljs/devtools';
import { App } from './App';
import './styles.css';

// Instrument before the pool's first task call — the sink must be installed
// when workers spawn for their events to forward over the task channel.
// No-op unless the URL carries ?__atoll_devtools.
initDevtools({
  session: { name: 'incidents-solid', framework: 'solid' },
  // Relative dashboard path — mounted hosts (the docs demo tree) ship
  // __atoll/ inside the app's own folder; absolute /__atoll/ would escape
  // a sub-path mount like consumer/<demo>/.
  overlay: { src: '__atoll/?mini=1' },
});

render(() => <App />, document.getElementById('root')!);
