// packages/angular-island/src/index.ts
/**
 * `@jwhenry123/mesh-angular-island` — the Angular shell surface for
 * `@jwhenry123/mesh-worker-dom` islands: a worker-hosted React (or
 * imperative proxy-DOM) tree mounted as an ordinary element in a
 * main-thread Angular app.
 *
 * ```ts
 * import { Component } from '@angular/core';
 * import { connectIslandWorker } from '@jwhenry123/mesh-worker-dom';
 * import { MeshIslandComponent } from '@jwhenry123/mesh-angular-island';
 *
 * const chartsWorker = () =>
 *   new Worker(new URL('./render.worker.ts', import.meta.url), { type: 'module' });
 *
 * @Component({
 *   standalone: true,
 *   imports: [MeshIslandComponent],
 *   template: `<mesh-island
 *     [client]="client"
 *     app="charts"
 *     [props]="props"
 *     [onEvent]="onIslandEvent" />`,
 * })
 * export class DashboardComponent {
 *   readonly client = connectIslandWorker({ worker: chartsWorker });
 *   props = { width: 520 };
 *   onIslandEvent = (name: string, payload: unknown) => { ... };
 * }
 * ```
 *
 * Semantics (mirroring `@jwhenry123/mesh-react-island`):
 * - Mounting is async — `ngOnInit` hands the host element to `mountIsland`,
 *   which spawns the worker and replays the first op batch. `onReady`
 *   receives the `IslandHandle` once mounted; failures go to `onError`
 *   (or `console.error` when no `onError` is bound).
 * - `props` input changes call `island.updateProps` — deduped by
 *   JSON-serialized identity, so change detection re-delivering an equal
 *   props object costs no round-trip (props cross the wire serialized
 *   anyway, making that the honest equality).
 * - `onEvent`/`onActivity`/`onReady`/`onError`/`slots` are read at call time
 *   — rebinding fresh closures never remounts the worker.
 * - `app`/`client` changes remount the island (destroy + fresh mount);
 *   `ngOnDestroy` destroys the island — the worker terminates unless the
 *   client is SHARED (several islands on one client mount realms into one
 *   worker; the realm unmounts and the worker dies with the last island
 *   to leave).
 *
 * `MeshIslandDirective` (`[meshIsland]`) carries the same inputs and can be
 * applied to ANY host element (`<div meshIsland [client]="…"/>`);
 * `MeshIslandComponent` (`<mesh-island>`) is the same behavior with the
 * dedicated element selector — both inherit from a shared base so their
 * input surface and lifecycle are identical.
 */
import {
  Component,
  Directive,
  ElementRef,
  Input,
  NgModule,
  inject,
} from '@angular/core';
import type {
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
} from '@angular/core';
import { mountIsland } from '@jwhenry123/mesh-worker-dom';
import type { IslandClient, IslandHandle } from '@jwhenry123/mesh-worker-dom';

// Re-export the handle types consumers need to name — same courtesy as the
// React binding, so a second package import is never required.
export type { IslandClient, IslandHandle };

/**
 * Shared island-mounting behavior for `<mesh-island>` and `[meshIsland]`.
 *
 * Declared as a bare `@Directive()` (no selector) so Angular treats it as a
 * directive base class: its `@Input()` members and lifecycle hooks are
 * inherited by both subclasses, which supply only a selector.
 */
@Directive()
export abstract class MeshIslandBase implements OnInit, OnChanges, OnDestroy {
  /**
   * How to reach the worker — a pre-connected `IslandClient` from
   * `connectIslandWorker({ worker })`. Required. (Unlike the React binding,
   * this surface takes only a client: in Angular the worker factory is
   * naturally shared/provided at connection time, so the client — which can
   * also be SHARED across several islands in one worker — is the honest
   * contract.)
   */
  @Input() client!: IslandClient;
  /**
   * Registry app name — a key of the `apps` map passed to
   * `defineIslandWorker`. Optional against a realm worker
   * (`defineRealmWorker`), which resolves its single app regardless.
   */
  @Input() app?: string;
  /** Initial + updated root props — serialized to the worker. */
  @Input() props?: Record<string, unknown>;
  /**
   * Transclusion slots — a worker `<div data-mesh-slot="name">` hands its
   * real element to `slots[name](el)` so the shell can mount main-thread
   * content inside it. Called again with `null` on teardown.
   */
  @Input() slots?: Record<string, (el: HTMLElement | null) => void>;
  /** Island → shell channel: every `emit` op lands here. */
  @Input() onEvent?: (name: string, payload: unknown) => void;
  /** Fired after each applied op batch — stats hooks. */
  @Input() onActivity?: () => void;
  /** The mounted handle (pid, updateProps, flush, setMode…) once ready. */
  @Input() onReady?: (handle: IslandHandle) => void;
  /** Mount/update errors surface here instead of an unhandled rejection. */
  @Input() onError?: (err: unknown) => void;

  private readonly host = inject(ElementRef) as ElementRef<HTMLElement>;
  private island: IslandHandle | null = null;
  /** Invalidates in-flight mounts — bump on remount/destroy. */
  private mountSeq = 0;
  /** Wire identity of the last props actually sent — the dedupe key. */
  private sentPropsJson = '';

  /**
   * Slot callbacks are looked up at op-application time through this
   * delegate, so a rebound `slots` input takes effect without remounting —
   * the same trick the React binding uses for its portal proxy.
   */
  private readonly slotDelegate = new Proxy(
    {} as Record<string, (el: HTMLElement | null) => void>,
    {
      get: (_target, name: string) => (el: HTMLElement | null) =>
        this.slots?.[name]?.(el),
    },
  );

  ngOnInit(): void {
    this.mount();
  }

  ngOnChanges(changes: SimpleChanges): void {
    // ngOnChanges runs before ngOnInit for the initial bindings — there is
    // no island yet; the pending mount reads the current inputs directly.
    if (this.island === null && this.mountSeq === 0) return;
    if ('app' in changes || 'client' in changes) {
      // A different app or worker connection is a different island.
      this.island?.destroy();
      this.island = null;
      this.mount();
      return;
    }
    if ('props' in changes) this.pushProps();
  }

  ngOnDestroy(): void {
    this.mountSeq++; // a late-resolving mount destroys itself instead
    const island = this.island;
    this.island = null;
    island?.destroy();
  }

  private mount(): void {
    const seq = ++this.mountSeq;
    const el = this.host.nativeElement;
    const client = this.client;
    if (client === undefined || client === null) {
      this.report(
        new Error('[meshIsland] requires a `client` input — see connectIslandWorker'),
      );
      return;
    }
    const propsJson = JSON.stringify(this.props ?? {});
    void (async () => {
      try {
        const handle = await mountIsland({
          client,
          el,
          app: this.app,
          props: this.props ?? {},
          onEvent: (name, payload) => this.onEvent?.(name, payload),
          onActivity: () => this.onActivity?.(),
          slots: this.slotDelegate,
        });
        if (seq !== this.mountSeq) {
          // Destroyed/remounted while the worker was still mounting.
          handle.destroy();
          return;
        }
        this.island = handle;
        this.sentPropsJson = propsJson;
        this.onReady?.(handle);
        // `props` may have changed while the mount was in flight — pushProps
        // dedupes, so this is a no-op unless it did.
        this.pushProps();
      } catch (err) {
        if (seq === this.mountSeq) this.report(err);
      }
    })();
  }

  private pushProps(): void {
    const json = JSON.stringify(this.props ?? {});
    if (json === this.sentPropsJson) return;
    this.sentPropsJson = json;
    this.island?.updateProps(this.props ?? {}).catch((err) => {
      if (this.onError !== undefined) this.onError(err);
      else console.error('[meshIsland] updateProps failed:', err);
    });
  }

  private report(err: unknown): void {
    if (this.onError !== undefined) this.onError(err);
    else console.error('[meshIsland] mount failed:', err);
  }
}

/**
 * `<mesh-island [client]="…" app="charts" [props]="…"/>` — a worker island as
 * a standalone element. All inputs are inherited from {@link MeshIslandBase}.
 */
@Component({
  selector: 'mesh-island',
  standalone: true,
  // No template — the island owns the host element's contents; Angular
  // projects nothing into it.
  template: '',
})
export class MeshIslandComponent extends MeshIslandBase {}

/**
 * `<div meshIsland [client]="…" [props]="…"/>` — the same island lifecycle as
 * an attribute directive, for hosts that need their own tag/attributes.
 */
@Directive({
  selector: '[meshIsland]',
  standalone: true,
})
export class MeshIslandDirective extends MeshIslandBase {}

/**
 * NgModule re-export of the standalone pair for apps still organized around
 * NgModules:
 *
 *   @NgModule({ imports: [MeshIslandModule] })
 *   export class AppModule {}
 *
 * Standalone imports (`imports: [MeshIslandComponent]`) remain the primary
 * interface — the module exists purely for NgModule-era codebases, matching
 * `MeshModule` in @jwhenry123/mesh-angular.
 */
@NgModule({
  imports: [MeshIslandComponent, MeshIslandDirective],
  exports: [MeshIslandComponent, MeshIslandDirective],
})
export class MeshIslandModule {}

// packages/solid-island/src/index.ts
/**
 * `@jwhenry123/mesh-solid-island` — the Solid shell surface for
 * `@jwhenry123/mesh-worker-dom` islands: a worker-hosted React (or
 * imperative proxy-DOM) tree mounted as an ordinary element in a
 * main-thread Solid app.
 *
 * ```tsx
 * import { createIsland } from '@jwhenry123/mesh-solid-island';
 * import { ChartsApp } from './worker/apps'; // the islandApp-stamped component
 *
 * const renderWorker = () =>
 *   new Worker(new URL('./render.worker.ts', import.meta.url), { type: 'module' });
 *
 * function Shell() {
 *   const island = createIsland({
 *     worker: renderWorker,
 *     app: ChartsApp,                     // or the registry name string 'charts'
 *     props: () => ({ width: 520 }),      // accessor — updates reach the worker
 *     onEvent: (name, payload) => console.log(name, payload),
 *   });
 *   return <div ref={island.ref} />;
 * }
 * ```
 *
 * Semantics (mirrors @jwhenry123/mesh-react-island):
 * - Mounting is async — `ref` mounts the island as soon as Solid assigns the
 *   container element; `status[0]()` moves 'mounting' → 'ready' | 'error'.
 * - `props` changes call `island.updateProps` — deduped by JSON-serialized
 *   identity, so re-tracking an equal props object costs no round-trip (props
 *   cross the wire serialized anyway, making that the honest equality).
 *   `props` may be a plain value, an accessor `() => props`, or a reactive
 *   getter on the options object — the watch effect tracks whatever it reads.
 * - `onEvent`/`onActivity`/`onReady`/`onError` are read through `options` at
 *   call time — passing fresh closures never remounts the worker. `slots`
 *   hand back the real elements the worker marked `data-mesh-slot="name"`;
 *   render Solid content into them with `render(() => ..., el)` from
 *   'solid-js/web' (not pulled in here so the shell surface stays renderer-only).
 * - `app`/`worker`/`client` are MOUNT-STABLE — swap them via a keyed remount
 *   (`<Show keyed>`/control-flow remount), not by passing a new value mid-life.
 * - Owner cleanup destroys the island; the worker terminates unless the client
 *   is SHARED (several islands on one client mount realms into one worker —
 *   the realm unmounts and the worker dies with the last island to leave).
 */
import {
  createEffect,
  createSignal,
  onCleanup,
  untrack,
  type Accessor,
  type Signal,
} from 'solid-js';
import {
  connectIslandWorker,
  islandAppNameOf,
  mountIsland,
} from '@jwhenry123/mesh-worker-dom';
import type {
  IslandAppLike,
  IslandAppProps,
  IslandClient,
  IslandHandle,
  IslandWorkerOptions,
} from '@jwhenry123/mesh-worker-dom';

// Re-export the app-contract types the API is generic over, so consumers can
// name them without a second package import.
export type { IslandAppLike, IslandAppProps, IslandClient, IslandHandle };

/** What `app` accepts: the registry name, or a component/def to resolve. */
export type IslandAppRef<A> = A | string;

/** A reactive-read-friendly option: the value itself or an accessor for it. */
export type MaybeAccessor<T> = T | Accessor<T>;

export type IslandStatus = 'mounting' | 'ready' | 'error';

export interface CreateIslandOptions<A = string> {
  /**
   * Which app to mount — the `apps` registry key ('charts') or the app
   * itself (a component, an `islandApp(...)`-stamped def, `{ imperative }`).
   * A reference infers `props` from its own signature. Optional against a
   * `defineRealmWorker` (1:1) worker — its single app mounts regardless.
   */
  app?: IslandAppRef<A>;
  /**
   * How to reach the worker — either a bundler-detectable factory
   * `() => new Worker(new URL('./x.worker.ts', import.meta.url), { type: 'module' })`
   * (the common case) or a pre-connected `IslandClient`. Exactly one is required.
   */
  worker?: (() => Worker) | URL;
  client?: IslandClient;
  /** Extra pool options — concurrency, taskTimeout, respawn… (poolSize stays 1). */
  workerOptions?: IslandWorkerOptions;
  /**
   * Initial + updated root props — serialized to the worker. Pass an
   * accessor (`props: () => ({ … })`) or define `props` as a reactive getter
   * on the options object to push updates reactively; a plain object mounts
   * statically (later pushes still possible via the returned `updateProps`).
   */
  props?: MaybeAccessor<IslandAppProps<A>>;
  /** Island → shell channel: every `emit` op lands here. */
  onEvent?: (name: string, payload: unknown) => void;
  /** Fired after each applied op batch — stats hooks. */
  onActivity?: () => void;
  /**
   * Transclusion slots — a worker `<div data-mesh-slot="name">` hands its
   * real element to `slots[name]` (and `null` on teardown). The element
   * stays worker-owned; mount main-thread content inside it with
   * `render(() => <Widget/>, el)` from 'solid-js/web'.
   */
  slots?: Record<string, (el: HTMLElement | null) => void>;
  /** The mounted handle (pid, updateProps, flush, setMode…) once ready. */
  onReady?: (island: IslandHandle) => void;
  /** Mount/update errors surface here instead of an unhandled rejection. */
  onError?: (err: unknown) => void;
}

export interface CreateIslandResult {
  /**
   * Solid callback ref — `<div ref={island.ref} />`. Assigning the element
   * mounts the island; rebinding to a DIFFERENT element remounts into it.
   * (Solid never calls refs with `null` — teardown hangs off the owner's
   * `onCleanup`, not the ref.)
   */
  ref: (el: HTMLElement) => void;
  /** The mounted IslandHandle — `undefined` until the mount resolves. */
  handle: Accessor<IslandHandle | undefined>;
  /** `[get, set]` — 'mounting' → 'ready' | 'error'. */
  status: Signal<IslandStatus>;
  /** The last mount/update error, if any (`onError` fires too). */
  error: Accessor<unknown>;
  /**
   * Imperative props push — same wire path as a reactive `options.props`
   * change. Called before the island is ready, the props fold into the
   * mount instead of dropping.
   */
  updateProps: (props: Record<string, unknown>) => Promise<void>;
}

/**
 * The composable — wire `ref` to a container element and Solid's owner
 * tree owns the island's lifecycle:
 *
 * ```tsx
 * const island = createIsland({ worker, app: 'charts', props: () => ({ width: w() }) });
 * return <div ref={island.ref} />;
 * ```
 *
 * Must be called inside a reactive owner (a component body or `createRoot`) —
 * the props-watch effect and destroy-on-dispose semantics hang off it.
 */
export function createIsland<A = string>(
  options: CreateIslandOptions<A>,
): CreateIslandResult {
  const status: Signal<IslandStatus> = createSignal<IslandStatus>('mounting');
  const setStatus = status[1];
  const [error, setError] = createSignal<unknown>();
  const [handle, setHandle] = createSignal<IslandHandle>();

  let island: IslandHandle | undefined;
  let element: HTMLElement | undefined;
  /** Owner disposed — a mount resolving after this point self-destructs. */
  let disposed = false;
  /** Serialized props handed to mountIsland — the catch-up baseline. */
  let mountedJson: string | undefined;
  /** Newest serialized props the reactive layer asked for (dedupe cursor). */
  let sentJson: string | undefined;
  /** updateProps() before the island was ready — folded in around mount. */
  let pendingProps: Record<string, unknown> | undefined;

  const report = (err: unknown): void => {
    setError(() => err);
    if (options.onError !== undefined) options.onError(err);
    else console.error('[createIsland]', err);
  };
  const fail = (err: unknown): void => {
    setStatus('error');
    report(err);
  };

  // `options.props` may be a plain value, an accessor, or a reactive getter
  // on the options object (JSX component props compile to getters) — reading
  // it inside the watch effect below tracks whichever form the caller used.
  // A function-typed props VALUE can't be told apart from an accessor, but
  // props cross the wire serialized either way (functions never survive the
  // boundary), so functions-as-accessors is the honest reading.
  const resolveProps = (): Record<string, unknown> => {
    const p = options.props;
    const v = typeof p === 'function' ? (p as Accessor<unknown>)() : p;
    return (v ?? {}) as Record<string, unknown>;
  };

  // props → updateProps, deduped by wire-serialized identity (the same bytes
  // produce the same render — a repeat send is a wasted round-trip).
  createEffect(() => {
    const props = resolveProps(); // tracked read — see resolveProps above
    const json = JSON.stringify(props);
    untrack(() => {
      if (json === sentJson) return;
      sentJson = json;
      // `island` is undefined while the mount is in flight — the post-mount
      // catch-up re-reads props against `mountedJson`, so nothing is lost.
      island?.updateProps(props).catch(report);
    });
  });

  async function mount(el: HTMLElement): Promise<void> {
    // `app`/`worker`/`client` are read once, untracked — mount-stable like
    // the React binding; swap them by remounting (keyed control flow).
    const appName = options.app === undefined ? 'main' : islandAppNameOf(options.app);
    if (appName === undefined) {
      fail(
        new Error(
          'createIsland could not resolve an app name — pass the registry key or stamp the app with islandApp(name, app)',
        ),
      );
      return;
    }
    const client =
      options.client ??
      (options.worker !== undefined
        ? connectIslandWorker({ worker: options.worker, ...options.workerOptions })
        : undefined);
    if (client === undefined) {
      fail(new Error('createIsland requires either `worker` or `client`'));
      return;
    }

    setStatus('mounting');
    const initialProps = pendingProps ?? resolveProps();
    pendingProps = undefined;
    mountedJson = JSON.stringify(initialProps);
    sentJson = mountedJson;

    let h: IslandHandle;
    try {
      h = await mountIsland({
        client,
        el,
        app: appName,
        props: initialProps,
        // Read through `options` at call time — fresh closures each render
        // never force a remount.
        onEvent: (name, payload) => options.onEvent?.(name, payload),
        onActivity: () => options.onActivity?.(),
        slots: options.slots,
      });
    } catch (err) {
      if (!disposed) fail(err);
      return;
    }
    if (disposed) {
      h.destroy();
      return;
    }
    island = h;
    setHandle(() => h);

    // Catch-up — props moved (or updateProps ran) while the mount was in
    // flight. Compared against what mountIsland actually received, not the
    // dedupe cursor: a dropped in-flight send still lands here.
    const latest = pendingProps ?? resolveProps();
    pendingProps = undefined;
    if (JSON.stringify(latest) !== mountedJson) {
      sentJson = JSON.stringify(latest);
      try {
        await h.updateProps(latest);
      } catch (err) {
        report(err);
      }
    }
    // The owner may have been disposed mid-await — its cleanup already ran
    // destroy(), so leave the handle alone (IslandHandle.destroy is NOT
    // idempotent — a second call would corrupt the shared-client refcount).
    if (disposed) return;
    setStatus('ready');
    options.onReady?.(h);
  }

  const ref = (el: HTMLElement): void => {
    if (el === element) return;
    // Rebinding to a different element remounts — release the old realm (and
    // its worker, when the client isn't shared) before the fresh mount.
    if (island !== undefined) {
      island.destroy();
      island = undefined;
      setHandle(() => undefined);
    }
    element = el;
    void mount(el);
  };

  onCleanup(() => {
    disposed = true;
    island?.destroy();
    island = undefined;
    element = undefined;
    setHandle(() => undefined);
  });

  const updateProps = (props: Record<string, unknown>): Promise<void> => {
    sentJson = JSON.stringify(props);
    if (island === undefined) {
      // Pre-mount (ref not bound or mount in flight) — folded into the
      // initial props or the post-mount catch-up, never dropped.
      pendingProps = props;
      return Promise.resolve();
    }
    return island.updateProps(props).catch((err: unknown) => report(err));
  };

  return { ref, handle, status, error, updateProps };
}

export interface IslandProps<A = string> extends CreateIslandOptions<A> {
  /**
   * Document the container div is created in — defaults to the ambient
   * `document`. Only needed in exotic embeddings (in-process worker tests
   * where a proxy document claims the global while a realm is active).
   */
  document?: Document;
}

/**
 * The no-JSX component form — `Island(options)` returns a real `<div>` the
 * island mounts into, usable as a Solid component (`<Island …/>`, where
 * `props`/callbacks stay reactive through Solid's props getters) or called
 * directly for the element. No container attributes/children — for those,
 * prefer `<div ref={island.ref} class="…" />` with `createIsland` directly.
 */
export function Island<A = string>(options: IslandProps<A>): HTMLElement {
  const island = createIsland(options);
  const el = (options.document ?? document).createElement('div');
  island.ref(el);
  return el;
}

export default Island;
