// examples/react-dom-worker/src/svelte-shell.ts
/**
 * Entry for svelte-shell.html — mounts the Svelte shell component.
 * All the interesting wiring lives in ./svelte/Shell.svelte.
 */
import { mount } from 'svelte';
import { initDevtools } from '@atolljs/devtools';
import Shell from './svelte/Shell.svelte';

// Sink before the shell mounts any island — workers only forward events
// when the flag reaches them at INIT. No-op without ?__atoll_devtools.
initDevtools({
  session: { name: 'islands-svelte-shell', framework: 'svelte' },
  overlay: { src: '__atoll/?mini=1' },
});

const rootEl = document.getElementById('root');
if (rootEl) mount(Shell, { target: rootEl });

// examples/react-dom-worker/src/vue-shell.ts
/**
 * Entry for vue-shell.html — mounts the Vue shell SFC.
 * All the interesting wiring lives in ./vue/Shell.vue.
 */
import { createApp } from 'vue';
import { initDevtools } from '@atolljs/devtools';
import Shell from './vue/Shell.vue';

// Sink before the shell mounts any island — workers only forward events
// when the flag reaches them at INIT. No-op without ?__atoll_devtools.
initDevtools({
  session: { name: 'islands-vue-shell', framework: 'vue' },
  overlay: { src: '__atoll/?mini=1' },
});

const rootEl = document.getElementById('root');
if (rootEl) createApp(Shell).mount(rootEl);
