// examples/vue/src/App.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useIncidents } from './useIncidents';
import { fmtDur, fmtInt, incidentColumns as columns, REGIONS, SERVICES, SEVERITIES, STATUSES, type QueryArgs } from '@jwhenry123/mesh/incidents';

const pageIndex = ref(0);
const pageSize = ref(50);
const sortBy = ref<string | null>(null);
const sortDesc = ref(false);
const severity = ref<number | ''>('');
const status = ref<number | ''>('');
const region = ref<number | ''>('');
const service = ref<number | ''>('');
const search = ref('');
const debouncedSearch = ref('');

// Any filter change restarts pagination
watch([severity, status, region, service], () => (pageIndex.value = 0));

// Debounce the site search box
let debounce: ReturnType<typeof setTimeout> | undefined;
function onSearch(e: Event) {
  const v = (e.target as HTMLInputElement).value.toUpperCase();
  search.value = v;
  clearTimeout(debounce);
  debounce = setTimeout(() => {
    debouncedSearch.value = v;
    pageIndex.value = 0;
  }, 300);
}

const query = computed<QueryArgs>(() => ({
  offset: pageIndex.value * pageSize.value,
  limit: pageSize.value,
  sortBy: sortBy.value,
  sortDesc: sortDesc.value,
  severity: severity.value === '' ? null : Number(severity.value),
  status: status.value === '' ? null : Number(status.value),
  region: region.value === '' ? null : Number(region.value),
  service: service.value === '' ? null : Number(service.value),
  search: debouncedSearch.value,
}));

const { ready, seedProgress, metrics, page, roundTripMs, isFetching } = useIncidents(query);

const rows = computed(() => page.value?.rows ?? []);
const filtered = computed(() => page.value?.filtered ?? 0);
const total = computed(() => page.value?.total ?? 0);
const pageCount = computed(() => Math.max(1, Math.ceil(filtered.value / pageSize.value)));
const timing = computed(() =>
  page.value && roundTripMs.value != null
    ? `scan ${page.value.scanMs.toFixed(0)}ms + sort ${page.value.sortMs.toFixed(0)}ms, round-trip ${roundTripMs.value.toFixed(0)}ms`
    : ''
);

function toggleSort(key: string) {
  if (sortBy.value !== key) {
    sortBy.value = key;
    sortDesc.value = false;
  } else if (!sortDesc.value) {
    sortDesc.value = true;
  } else {
    sortBy.value = null;
  }
}
const prevPage = () => { if (pageIndex.value > 0) pageIndex.value--; };
const nextPage = () => { if (pageIndex.value < pageCount.value - 1) pageIndex.value++; };
</script>

<template>
  <main v-if="!ready">
    <h1>Telecom Incident Explorer</h1>
    <p class="subtitle">Seeding 1,000,000 incident records into shared memory…</p>
    <div class="progress"><div class="progress-fill" :style="{ width: `${seedProgress}%` }" /></div>
    <p class="subtitle">{{ fmtInt(seedProgress) }}% — {{ fmtInt(seedProgress * 10_000) }} records</p>
  </main>

  <main v-else class="wide">
    <h1>Telecom Incident Explorer</h1>
    <p class="subtitle">
      {{ fmtInt(total) }} fixed-layout records in shared memory — the worker filters, sorts, and aggregates;
      only the visible page crosses postMessage.
    </p>

    <div class="metrics">
      <div class="metric"><span class="metric-value">{{ metrics ? fmtInt(metrics.total) : '—' }}</span><span>total</span></div>
      <div class="metric"><span class="metric-value st-open">{{ metrics ? fmtInt(metrics.open) : '—' }}</span><span>open</span></div>
      <div class="metric"><span class="metric-value st-ack">{{ metrics ? fmtInt(metrics.acknowledged) : '—' }}</span><span>acknowledged</span></div>
      <div class="metric"><span class="metric-value st-resolved">{{ metrics ? fmtInt(metrics.resolved) : '—' }}</span><span>resolved</span></div>
      <div class="metric"><span class="metric-value sev-critical">{{ metrics ? fmtInt(metrics.critical) : '—' }}</span><span>critical</span></div>
      <div class="metric"><span class="metric-value">{{ metrics ? fmtInt(metrics.customersAffected) : '—' }}</span><span>customers</span></div>
      <div class="metric"><span class="metric-value">{{ metrics ? fmtDur(metrics.avgDurationMin) : '—' }}</span><span>avg duration</span></div>
    </div>
    <p v-if="metrics" class="subtitle">
      metrics aggregated by worker in {{ metrics.scanMs.toFixed(0) }}ms{{ timing ? ` · last query: ${timing}` : '' }}
    </p>

    <div class="toolbar">
      <select v-model="severity">
        <option value="">all severities</option>
        <option v-for="(s, i) in SEVERITIES" :key="s" :value="i">{{ s }}</option>
      </select>
      <select v-model="status">
        <option value="">all statuses</option>
        <option v-for="(s, i) in STATUSES" :key="s" :value="i">{{ s }}</option>
      </select>
      <select v-model="region">
        <option value="">all regions</option>
        <option v-for="(s, i) in REGIONS" :key="s" :value="i">{{ s }}</option>
      </select>
      <select v-model="service">
        <option value="">all services</option>
        <option v-for="(s, i) in SERVICES" :key="s" :value="i">{{ s }}</option>
      </select>
      <input type="text" placeholder="search site…" :value="search" @input="onSearch" />
      <span class="filtered">{{ fmtInt(filtered) }} matching{{ isFetching ? ' · updating…' : '' }}</span>
    </div>

    <table>
      <thead>
        <tr>
          <th v-for="col in columns" :key="col.key" class="sortable" @click="toggleSort(col.key)">
            {{ col.label }}{{ sortBy === col.key ? (sortDesc ? ' ▼' : ' ▲') : '' }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="row in rows" :key="row.id">
          <td v-for="col in columns" :key="col.key">
            <span v-if="col.badge" class="badge" :class="col.badge(row)">{{ col.text(row) }}</span>
            <template v-else>{{ col.text(row) }}</template>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="pager">
      <button :disabled="pageIndex === 0" @click="prevPage">‹ prev</button>
      <span>page {{ pageIndex + 1 }} / {{ pageCount }}</span>
      <button :disabled="pageIndex >= pageCount - 1" @click="nextPage">next ›</button>
      <select v-model="pageSize">
        <option v-for="s in [25, 50, 100, 200]" :key="s" :value="s">{{ s }} / page</option>
      </select>
    </div>
  </main>
</template>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { createIncidents } from './incidents.svelte';
  import { fmtDur, fmtInt, incidentColumns as columns, REGIONS, SERVICES, SEVERITIES, STATUSES, type QueryArgs } from '@jwhenry123/mesh/incidents';

  let pageIndex = $state(0);
  let pageSize = $state(50);
  let sortBy = $state<string | null>(null);
  let sortDesc = $state(false);
  let severity = $state<number | ''>('');
  let status = $state<number | ''>('');
  let region = $state<number | ''>('');
  let service = $state<number | ''>('');
  let search = $state('');
  let debouncedSearch = $state('');

  // Debounce the site search box
  let debounce: ReturnType<typeof setTimeout>;
  function onSearch(e: Event) {
    const v = (e.currentTarget as HTMLInputElement).value.toUpperCase();
    search = v;
    clearTimeout(debounce);
    debounce = setTimeout(() => { debouncedSearch = v; pageIndex = 0; }, 300);
  }

  const query: QueryArgs = $derived({
    offset: pageIndex * pageSize,
    limit: pageSize,
    sortBy,
    sortDesc,
    severity: severity === '' ? null : Number(severity),
    status: status === '' ? null : Number(status),
    region: region === '' ? null : Number(region),
    service: service === '' ? null : Number(service),
    search: debouncedSearch,
  });

  const inc = createIncidents(() => query);

  const rows = $derived(inc.page?.rows ?? []);
  const filtered = $derived(inc.page?.filtered ?? 0);
  const total = $derived(inc.page?.total ?? 0);
  const pageCount = $derived(Math.max(1, Math.ceil(filtered / pageSize)));
  const timing = $derived(
    inc.page && inc.roundTripMs != null
      ? `scan ${inc.page.scanMs.toFixed(0)}ms + sort ${inc.page.sortMs.toFixed(0)}ms, round-trip ${inc.roundTripMs.toFixed(0)}ms`
      : ''
  );

  // Any filter change restarts pagination
  const resetPage = () => (pageIndex = 0);

  function toggleSort(key: string) {
    if (sortBy !== key) { sortBy = key; sortDesc = false; }
    else if (!sortDesc) sortDesc = true;
    else sortBy = null;
  }
  const prevPage = () => { if (pageIndex > 0) pageIndex--; };
  const nextPage = () => { if (pageIndex < pageCount - 1) pageIndex++; };
</script>

{#if !inc.ready}
  <main>
    <h1>Telecom Incident Explorer</h1>
    <p class="subtitle">Seeding 1,000,000 incident records into shared memory…</p>
    <div class="progress"><div class="progress-fill" style="width: {inc.seedProgress}%"></div></div>
    <p class="subtitle">{fmtInt(inc.seedProgress)}% — {fmtInt(inc.seedProgress * 10_000)} records</p>
  </main>
{:else}
  <main class="wide">
    <h1>Telecom Incident Explorer</h1>
    <p class="subtitle">
      {fmtInt(total)} fixed-layout records in shared memory — the worker filters, sorts, and aggregates;
      only the visible page crosses postMessage.
    </p>

    <div class="metrics">
      <div class="metric"><span class="metric-value">{inc.metrics ? fmtInt(inc.metrics.total) : '—'}</span><span>total</span></div>
      <div class="metric"><span class="metric-value st-open">{inc.metrics ? fmtInt(inc.metrics.open) : '—'}</span><span>open</span></div>
      <div class="metric"><span class="metric-value st-ack">{inc.metrics ? fmtInt(inc.metrics.acknowledged) : '—'}</span><span>acknowledged</span></div>
      <div class="metric"><span class="metric-value st-resolved">{inc.metrics ? fmtInt(inc.metrics.resolved) : '—'}</span><span>resolved</span></div>
      <div class="metric"><span class="metric-value sev-critical">{inc.metrics ? fmtInt(inc.metrics.critical) : '—'}</span><span>critical</span></div>
      <div class="metric"><span class="metric-value">{inc.metrics ? fmtInt(inc.metrics.customersAffected) : '—'}</span><span>customers</span></div>
      <div class="metric"><span class="metric-value">{inc.metrics ? fmtDur(inc.metrics.avgDurationMin) : '—'}</span><span>avg duration</span></div>
    </div>
    {#if inc.metrics}
      <p class="subtitle">metrics aggregated by worker in {inc.metrics.scanMs.toFixed(0)}ms{timing ? ` · last query: ${timing}` : ''}</p>
    {/if}

    <div class="toolbar">
      <select bind:value={severity} onchange={resetPage}>
        <option value="">all severities</option>
        {#each SEVERITIES as s, i}<option value={i}>{s}</option>{/each}
      </select>
      <select bind:value={status} onchange={resetPage}>
        <option value="">all statuses</option>
        {#each STATUSES as s, i}<option value={i}>{s}</option>{/each}
      </select>
      <select bind:value={region} onchange={resetPage}>
        <option value="">all regions</option>
        {#each REGIONS as s, i}<option value={i}>{s}</option>{/each}
      </select>
      <select bind:value={service} onchange={resetPage}>
        <option value="">all services</option>
        {#each SERVICES as s, i}<option value={i}>{s}</option>{/each}
      </select>
      <input type="text" placeholder="search site…" value={search} oninput={onSearch} />
      <span class="filtered">{fmtInt(filtered)} matching{inc.isFetching ? ' · updating…' : ''}</span>
    </div>

    <table>
      <thead>
        <tr>
          {#each columns as col (col.key)}
            <th class="sortable" onclick={() => toggleSort(col.key)}>
              {col.label}{sortBy === col.key ? (sortDesc ? ' ▼' : ' ▲') : ''}
            </th>
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each rows as row (row.id)}
          <tr>
            {#each columns as col (col.key)}
              <td>
                {#if col.badge}<span class="badge {col.badge(row)}">{col.text(row)}</span>{:else}{col.text(row)}{/if}
              </td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>

    <div class="pager">
      <button onclick={prevPage} disabled={pageIndex === 0}>‹ prev</button>
      <span>page {pageIndex + 1} / {pageCount}</span>
      <button onclick={nextPage} disabled={pageIndex >= pageCount - 1}>next ›</button>
      <select bind:value={pageSize}>
        {#each [25, 50, 100, 200] as s}<option value={s}>{s} / page</option>{/each}
      </select>
    </div>
  </main>
{/if}
